### ISSUE TITLE
QGIS Crashes When Running NNJoin

### ISSUE THREAD

**Issue by jimjam-slam** [havatv/qgisnnjoinplugin#1]
When running NNJoin 1.2.0 in QGIS 2.6.0 on OS X Yosemite 10.10.1, QGIS crashes when clicking 'OK" in the NNJoin dialog.
![screenshot 2014-12-11 11 48 28](https://cloud.githubusercontent.com/assets/6520659/5387278/a7e7e980-812b-11e4-87d9-b80167488f93.png)

![screenshot 2014-12-11 11 49 05](https://cloud.githubusercontent.com/assets/6520659/5387282/b8b67542-812b-11e4-9fc3-32a0ed735e09.png)

This has been reproduced on two different systems, each running the same versions of NNJoin and OS X. They're running either QGIS 2.6.0 or 2.6.1.

Would a crash report be helpful?

**Comment by havatv** [comment]
Thank you for reporting this.  I don't have OS X available here, so I can't test on that OpSys.
NNJoin seems to work OK on both Windows 7 and Ubuntu 14.04 with QGIS 2.6.1.
Can you see something useful in the NNJoin tab in the Log Messages panel (open it using View-> Panels-> Log Messages) before the crash?

**Comment by havatv** [comment]
@rensa, could you test the plugin using the test data sets that you find under the tests directory?
If you could send me your data sets, that could be helpful for debugging.

**Comment by jimjam-slam** [comment]
Hi @havatv, sorry for the delay. Just ran NNJoin with the test data and got the same result. Before the crash, with the NNJoin dialog open, the log looks like this:

2014-12-16T14:33:32 0   QGIS starting...
2014-12-16T14:33:32 0   Python support ENABLED :-) 
2014-12-16T14:33:33 0   Application state:
            QGIS_PREFIX_PATH env var:  
            Prefix:     /Applications/QGIS.app/Contents/MacOS
            Plugin Path:        /Applications/QGIS.app/Contents/MacOS/../PlugIns/qgis
            Package Data Path:  /Applications/QGIS.app/Contents/MacOS/../Resources
            Active Theme Name:  default
            Active Theme Path:  :/images/themes/default/
            Default Theme Path: :/images/themes/default/
            SVG Search Paths:   /Applications/QGIS.app/Contents/MacOS/../Resources/svg/
                    /Users/rensa/.qgis2//svg/
            User DB Path:   /Applications/QGIS.app/Contents/MacOS/../Resources/resources/qgis.db

2014-12-16T14:33:33 0   QGIS Ready!

QGIS usually beachballs for a few seconds the first time it crashes this way upon starting OS X up; on subsequent tries it crashes immediately.

**Comment by kubakrukar** [comment]
Same problem here on the same system specs (I haven't checked on the test data though - happy to do it if needed). End of the day I installed the Windows version under Parallels Desktop. Having tried the existing alternatives to the NNJoin operation (GRASS v.dist, and QChainage+Distance Matrix), it's quicker and more user friendly to beg colleagues for 5 minutes with their PCs, really.

**Comment by jimjam-slam** [comment]
I already have ArcGIS on a VM, so nothing's critical for me, but I really loathe ArcGIS, so I'm persevering with moving to QGIS ;)

**Comment by havatv** [comment]
Thank you again for following up on this.  Since the plugin works on all my platforms, it is difficult for me to find the source of the error.
I don't know if this could be a missing dependency.  I am working on a new version, so if you would like to test it, I can mail it to you.

**Comment by kubakrukar** [comment]
Hi Havard,

Yes, I will be happy to test it. I’m a member of a larger community of researchers for whom Nearest Neighbour Join is an often used operation and many people can’t migrate from ArcGIS even if they want to.

Thanks for your fantastic contribution with the plugin.

Best wishes,
Jakub    /github: kubakrukar

---

Jakub Krukar
PhD Candidate \
psychology+architecture \
Northumbria University, Newcastle, UK \
www.UsableSpaces.net

**Comment by havatv** [comment]
@rensa, if you have a crash report, I can try to have a look.

**Comment by havatv** [comment]
I have uploaded a new version (1.2.2) of the plugin with some small changes.  I doubt that this issue has been addressed, but it would be nice if someone could check.

**Comment by kubakrukar** [comment]
It worked very well this time! (same data set as previously, QGIS updated to 2.6.1, Mac OS Yosemite)
Thanks, this is really helpful!

**Comment by havatv** [comment]
Glad to hear that it worked now.  Thank you for testing, @kubakrukar.  I close the issue

**Comment by windyuers** [comment]
Hello, havatv

I met a similar crashed issue as above. it occured at two different computers. i guess if the volume of my data was too large (input vector layer contains 49568 pieces of data). the below is the report. I'm looking forward to your reply and suggestions. thanks in advance.
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003c18 (most recent call first):
  File "C:\Users/Xingchen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_gui.py", line 585 in showError
    self.iface.messageBar().pushMessage(self.tr('Error'), text,
  File "C:\Users/Xingchen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_gui.py", line 221 in workerFinished
    self.showError(self.tr('Aborted') + '!')
  File "C:\Users/Xingchen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_plugin.py", line 177 in run
    self.dlg.exec_()
```


**Stack Trace**

```

QVariantAnimation::endValue :
QFocusFrame::trUtf8 :
QToolBar::widgetForAction :
QTabBarPrivate::~QTabBarPrivate :
QTabBarPrivate::isAnimated :
QLayoutPrivate::doResize :
QLayout::activate :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QgsMessageBar::showItem :
QgsMessageBar::pushItem :
QgsMessageBar::pushMessage :
QgsPresetSchemeColorRamp::clone :
PyArg_ParseTuple_SizeT :
PyObject_MakeTpCall :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
