### ISSUE TITLE
Display of plugin on high resolution monitor

### ISSUE THREAD

**Issue by ImpactGIS** [havatv/qgisnnjoinplugin#10]
Hi,

Love the plugin!! I am using the plugin with QGIS 2.18.6 on a Dell 27 inch 5K monitor with Windows 10 and the plugin does not display correctly. It appears that it does not scale the bounding boxes for the text (see image).

I am guessing that the issue relates to the scaling of the text elements that is done by windows for high resolution monitors, I have scaling set to 200% most of the time.

Thanks!!

Nigel
 
![image](https://user-images.githubusercontent.com/31126799/29451094-4bcc17ec-83f9-11e7-8efb-1fcdcec97cd3.png)

**Comment by havatv** [comment]
That does not look good!  I had hoped that QT would take care of high-res issues, but I will try to look into it, but I do not have access to a high-res diplay.  If you have examples of Python plugins that work well on high-res displays, that could help.
Thank's for reporting!

**Comment by ImpactGIS** [comment]
Thanks! I will look into it and get back to you with a few examples.

**Comment by ImpactGIS** [comment]
Here are a couple of examples

[Multi Ring Buffer](https://github.com/HeikkiVesanto/QGIS_Multi_Ring_Buffer)
[Vector Bender](https://github.com/olivierdalang/VectorBender)

**Comment by havatv** [comment]
I have had a look at the example plugins you provided, and they seem to use less complex QT user interface designs.  So it may be a QT issue.  From your screen-shot, it seems as if all the "top level" components of the UI are OK, but that children of "top level" components get squeezed.
Does it help to make the plugin window larger?

**Comment by havatv** [comment]
Could show me what the Multi-distance buffer plugin and the Line Direction Histogram look like in high-res (they are also plugin that I have developed)?
They have a mix of atomic top level components and smaller and larger hierarchical components.

**Comment by ImpactGIS** [comment]
Just did a quick test with the Vector Bender and NN Join plugins.

Here is a screen grab of the two side by side on the 5K monitor:
![image](https://user-images.githubusercontent.com/31126799/29461609-3c858676-8424-11e7-932a-88fc8d19917e.png)

I am running a 24 inch 1920 x 1200 monitor too. And if I restart the computer with just this monitor connected this is what I see:
![image](https://user-images.githubusercontent.com/31126799/29461739-b09b99ce-8424-11e7-9460-ac6517c52939.png)


Just see your latest comment, I will forward screen grabs of those.

**Comment by havatv** [comment]
Good idea to provide both for comparison! Strange that the plugin looks the same in the non-high-res (1920x1200) mode.  Do you use 200% on both?
Have you tried to resize the plugin window (make it higher)?

**Comment by ImpactGIS** [comment]
Thanks!
Just the NNJoin plugin it would appear...
![image](https://user-images.githubusercontent.com/31126799/29461896-57e9de34-8425-11e7-9afb-e79d05379d18.png)

**Comment by havatv** [comment]
I have tried to remove the outer vertical layout (that should be obsolete).  I try to attach the updated version of the plugin.
You can test it by removing the NNJoin folder in the Python plugin folder (.qgis2/python/plugins) and unzip the zip file there.
[NNJoin.zip](https://github.com/havatv/qgisnnjoinplugin/files/1234621/NNJoin.zip)

**Comment by ImpactGIS** [comment]
Success!!

Looking much better now!! Thanks for sorting that so quickly and thanks again for a very handy plugin. I use it on an almost daily basis. 

![image](https://user-images.githubusercontent.com/31126799/29463347-49972a44-842a-11e7-8776-e386b277efaa.png)

**Comment by havatv** [comment]
Thanks for helping improve the plugin.
