### ISSUE TITLE
Sorting of elements

### ISSUE THREAD

**Issue by ImpactGIS** [havatv/qgisnnjoinplugin#11]
Hi again,

Plugin version 1.3.1

The elements within the dropdown lists are in what appears to be random order. Is it possible to sort these either alphabetically or the same as the QGIS Layers panel?

Thanks

Nigel

![image](https://user-images.githubusercontent.com/31126799/29452077-effaea84-83fc-11e7-93c8-de0c1071092f.png)

**Comment by havatv** [comment]
Thank you for your interest in the plugin and for reporting.  I agree that the current "sorting" is not convenient when you have many layers.  I will look into it.

**Comment by havatv** [comment]
The layers will now appear in the same order as in the Layers Panel.
