### ISSUE TITLE
The points don't move to new place

### ISSUE THREAD

**Issue by ghost** [havatv/qgisnnjoinplugin#12]
I tried the NNJoin plugin on OSM data transformed to EPSG:23700 CRS.
I would like to join fuels (points) to roads (linestring), but the points' place in the output didn't change. The distance field is correct by the way. What can be the problem?

**Comment by havatv** [comment]
Thank you for your interest in the NNJoin plugin, @ewirth !
The NNJoin plugin will not move the points. For each point in the input layer, it will find the spatially nearest object in the join layer and calculate the distance to it's geometry.  The points in the resulting point layer will have the same geometries and attributes as those in the input layer, but they will also have all the attributes of the nearest object in the join layer included, plus the distance to that object.
The plugin help page provides more information about how the plugin works.
