### ISSUE TITLE
pendingFields() does not exist any more

### ISSUE THREAD

**Issue by rogorido** [havatv/qgisnnjoinplugin#13]
Many thanks for your plugin. Could you maybe adapt it to use the new API of qgis3? More exactly, pendingFields() does not exist any more and should be replaced by fields().

https://github.com/qgis/QGIS/blob/master/doc/api_break.dox

Thanks in advance!

**Comment by havatv** [comment]
Thank you for reporting, @rogorido .  It is some time since I used the plugin with QGIS 3.  I tested now, and got the same problem.  I will try to fix it.

**Comment by rogorido** [comment]
thanks!

**Comment by havatv** [comment]
That should fix it.  The new version is 3.0.4.

**Comment by rogorido** [comment]
thanks!

**Comment by havatv** [comment]
Version 3.0.4 is now uploaded to plugins.qgis.org. It has to be approved before it becomes available.
