### ISSUE TITLE
Call the plugin from PyQGIS

### ISSUE THREAD

**Issue by giacfalk** [havatv/qgisnnjoinplugin#20]
Is it possible to call the plugin programmatically from the Python Console?

**Comment by havatv** [comment]
Hi @giacfalk,
The current version of NNJoin is not a processing plugin, so you can not call it from the Python Console.
The NNJoin functionality has now been built into QGIS through a new processing algorithm, "Join attributes by nearest".  See https://github.com/qgis/QGIS/pull/9659. It is available in QGIS 3.8 (coming 2019-06-21). So I guess it is not any point in turning NNJoin into a processing plugin now.

**Comment by giacfalk** [comment]
That is great, thank you very much for the fast reply. And thanks for developing the plugin, so useful for years.
