### ISSUE TITLE
Include in Processing

### ISSUE THREAD

**Issue by ghtmtt** [havatv/qgisnnjoinplugin#21]
I really think your plugin should become a core algorithm of Processing (yeah I now it's not the first time I'm saying this :P )

**Comment by havatv** [comment]
Nyall has added the core algorithm "Join attributes by nearest". It should be a good replacement for NNJoin. It is available in QGIS 3.8, and supports "K-nearest neighbour joins".

**Comment by ghtmtt** [comment]
so the "Join attributes by nearest" is a replacement of NNJoin in your opinion? Thanks for pointing out ;)
