### ISSUE TITLE
showError not defined in getwkbtext

### ISSUE THREAD

**Issue by jott-al** [havatv/qgisnnjoinplugin#22]
Hello,

For a vector layer of "PointZ" type a Python error ("name 'showError' is not defined") is generated. I was able to fix it by changing line 570 in NNJoin_gui.py (else: in getwkbtext) from showError(...) to _self._showError(...).

Would it make sense to include PointZ in the list of supported types, and issue a warning that the z coordinate will be ignored?

Joerg

**Comment by havatv** [comment]
Should be fixed with https://github.com/havatv/qgisnnjoinplugin/pull/23.  Thanks, @jott-al!

**Comment by havatv** [comment]
More geometry types are supported with
https://github.com/havatv/qgisnnjoinplugin/commit/976aa42455bf184179b294ac4aa77b8d1b21c443
The fixes are included in version 3.1.3 that is now uploaded on plugins.qgis.org.
