### ISSUE TITLE
2nd or 3rd nearest?

### ISSUE THREAD

**Issue by dongwoohahm** [havatv/qgisnnjoinplugin#26]
Hi, I am trying to use nnjoin to solve the following task.
There are three layers:
1) Census tracts (polygons)
2) Census tract centroids (points)
3) School districts (polygons)
I want to find the closest school district (except for itself) for each census tract centroid.  However the situation is that all census tracts are contained in some school district so that NNJoin will return the school district in which the census tract centroid (or the census tract itself) is located.  I was guessing if there is a way to use NNjoin to do this kind of task?

Thanks a lot.

**Comment by havatv** [comment]
The QGIS algorithm "Join attributes by nearest" should be an option for you (it offers most of NNJoin's functionality and more). It is available in QGIS 3.8, and supports "K-nearest neighbour joins".

**Comment by dongwoohahm** [comment]
Thank you so much for your help.
