### ISSUE TITLE
NameError: name 'QMessageBox' is not defined

### ISSUE THREAD

**Issue by kadirsahbaz** [havatv/qgisnnjoinplugin#28]
`QMessageBox `should be imported in `NNJoin_gui.py`

`from qgis.PyQt.QtWidgets import QMessageBox`

The question about that issue: https://gis.stackexchange.com/q/381210/29431

**Comment by havatv** [comment]
@kadirsahbaz,which version of the plugin?
3.1.3 seems to be OK   —  no error messages or warnings

**Comment by kadirsahbaz** [comment]
Fixed now.
