### ISSUE TITLE
Same crasch issues with QGIS on Windows and Mac version

### ISSUE THREAD

**Issue by soli004** [havatv/qgisnnjoinplugin#7]
I have two point layers that I want to connect with columnsID data to link to each other with a line.
But QGIS crasches as soon as I press OK to run the process, I have tried with QGIS v 2.18.2 on both Mac and Windows and I have same problems. Anyone else seen this?

Regards
Soren

**Comment by havatv** [comment]
Thank you for reporting, @soli004.  If you can share the two point data sets, I can do some testing.

Håvard

**Comment by havatv** [comment]
It is difficult to get further with the information that is provided, so I will close the issue as "invalid".  Please reopen with more information if this is still relevant.
